"""create practice_sessions table

Revision ID: 99596986f14a
Revises: a5ec041807cc
Create Date: 2026-07-21 07:39:54.169000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99596986f14a'
down_revision: Union[str, None] = 'a5ec041807cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('impromptu', 'debate', 'interview', 'storytelling', name='sessionmode'), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'recording', 'processing', 'complete', 'failed', name='sessionstatus'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('audio_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_sessions_user_id'), 'practice_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_practice_sessions_user_id'), table_name='practice_sessions')
    op.drop_table('practice_sessions')
    # ### end Alembic commands ###

    # Autogenerate's default downgrade body does NOT drop the native
    # Postgres enum types it created in upgrade() — do it explicitly, or a
    # downgrade + re-upgrade cycle fails with "type already exists".
    sa.Enum(name='sessionmode').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sessionstatus').drop(op.get_bind(), checkfirst=True)
